name: "Publish"

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: "Publish CFN to S3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-beboptechnology-onboarding
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 900
          
      - name: Publish to S3
        id: publish
        run: aws s3 cp aws/cloudformation.yaml s3://bebop-oneclick-onboarding/cloudformation.yaml
